name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install ShellCheck
      run: sudo apt-get update && sudo apt-get install -y shellcheck
      
    - name: Make scripts executable
      run: chmod +x bootc-builder install.sh test.sh
      
    - name: Lint shell scripts
      run: make lint
      
    - name: Run tests
      run: make test
      
    - name: Test installation (dry run)
      run: ./install.sh --install-dir ./test-install
      
    - name: Verify installed script works
      run: ./test-install/bootc-builder --help

  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create release artifact
      run: |
        mkdir -p release
        cp bootc-builder install.sh README.md LICENSE release/
        tar -czf bootc-builder.tar.gz -C release .
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: bootc-builder
        path: bootc-builder.tar.gz
